# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Stack(object):
    def setupUi(self, Stack):
        Stack.setObjectName("Stack")
        Stack.resize(800, 360)
        self.centralwidget = QtWidgets.QWidget(Stack)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.But_rev = QtWidgets.QPushButton(self.centralwidget)
        self.But_rev.setObjectName("But_rev")
        self.gridLayout.addWidget(self.But_rev, 13, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 10, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 10, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 9, 0, 1, 2)
        self.in_string = QtWidgets.QLineEdit(self.centralwidget)
        self.in_string.setAlignment(QtCore.Qt.AlignCenter)
        self.in_string.setObjectName("in_string")
        self.gridLayout.addWidget(self.in_string, 12, 0, 1, 1)
        self.out_string = QtWidgets.QLineEdit(self.centralwidget)
        self.out_string.setAlignment(QtCore.Qt.AlignCenter)
        self.out_string.setReadOnly(True)
        self.out_string.setObjectName("out_string")
        self.gridLayout.addWidget(self.out_string, 12, 1, 1, 1)
        self.answer = QtWidgets.QLineEdit(self.centralwidget)
        self.answer.setAlignment(QtCore.Qt.AlignCenter)
        self.answer.setReadOnly(True)
        self.answer.setObjectName("answer")
        self.gridLayout.addWidget(self.answer, 8, 0, 1, 2)
        self.but_cal = QtWidgets.QPushButton(self.centralwidget)
        self.but_cal.setObjectName("but_cal")
        self.gridLayout.addWidget(self.but_cal, 6, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 2)
        self.portfix = QtWidgets.QLineEdit(self.centralwidget)
        self.portfix.setAlignment(QtCore.Qt.AlignCenter)
        self.portfix.setReadOnly(True)
        self.portfix.setObjectName("portfix")
        self.gridLayout.addWidget(self.portfix, 5, 1, 1, 1)
        self.infix = QtWidgets.QLineEdit(self.centralwidget)
        self.infix.setAlignment(QtCore.Qt.AlignCenter)
        self.infix.setObjectName("infix")
        self.gridLayout.addWidget(self.infix, 5, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        Stack.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Stack)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Stack.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Stack)
        self.statusbar.setObjectName("statusbar")
        Stack.setStatusBar(self.statusbar)

        self.retranslateUi(Stack)
        QtCore.QMetaObject.connectSlotsByName(Stack)

    def retranslateUi(self, Stack):
        _translate = QtCore.QCoreApplication.translate
        Stack.setWindowTitle(_translate("Stack", "Stack"))
        self.But_rev.setText(_translate("Stack", "Đảo"))
        self.label_5.setText(_translate("Stack", "Nhập xâu vào"))
        self.label_6.setText(_translate("Stack", "Xâu đảo ngược"))
        self.label_7.setText(_translate("Stack", "Tính giá trị biểu thức (Chuyển từ trung tố sang hậu tố)"))
        self.label_9.setText(_translate("Stack", "Biểu thức hậu tố"))
        self.label_8.setText(_translate("Stack", "Biểu thức trung tố (Các ký tự cách nhau bởi dấu cách)"))
        self.label_2.setText(_translate("Stack", "Đảo ngược xâu"))
        self.but_cal.setText(_translate("Stack", "Thực hiện tính toán"))
        self.label_10.setText(_translate("Stack", "Kết quả"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Stack = QtWidgets.QMainWindow()
    ui = Ui_Stack()
    ui.setupUi(Stack)
    Stack.show()
    sys.exit(app.exec_())

